### ISSUE TITLE
question about ctrl.ui property

### ISSUE THREAD

**Issue by yadimon** [kevinvanhove/angular-structure-styleguide#1]
in your code:
`$ctrl.ui.pauze = pauzeVideo;`
the `ui` property should be set somewhere. so what sets the property?
or its just example, that assumes, some initialization code?

**Comment by kevinvanhove** [comment]
Hi, i still have to write about the datamodel solutions but indeed the first function i call on loading a component is `setDataModel()`.

This is the signature of that function:

`
function setDataModel(){
   $ctrl.ui = {}
   $ctrl.data = {}
}
`

So yes, the ui property is set when the component loads... I will soon update the document and talk about the datamodel solutions... Thx for you're feedback...
